-- aggregate measure values by dimensions

-- find total customers by countries
select country,count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc;

-- find total customers by gender
select gender, count(customer_key) as total_customers
from gold.dim_customers
group by gender;

-- find total products by category
select category, count(product_key) as total_products
from gold.dim_products
group by category;

-- average cost in each category
select category,avg(cost) as average_cost
from gold.dim_products
group by category;

-- total revenue generated for each category
select p.category, sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key=p.product_key
group by p.category
order by total_revenue desc;

-- total revenue generated by each customer 
select c.customer_key, c.first_name,c.last_name,
sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key=c.customer_key
group by c.customer_key, c.first_name,c.last_name
order by total_revenue desc;

--what is the distribution of sold items across countries
select c.country, count(s.quantity) as total_sold_items
from gold.fact_sales s
join gold.dim_customers c
on c.customer_key = s.customer_key
group by c.country
order by total_sold_items desc;
